test v4.2.8

diff --git a/.github/workflows/v3_push_and_deploy.yaml b/.github/workflows/v3_push_and_deploy.yaml
--- a/.github/workflows/v3_push_and_deploy.yaml
+++ b/.github/workflows/v3_push_and_deploy.yaml
@@ -100,6 +100,30 @@ jobs:
     runs-on: ubuntu-latest
     needs: build-push-image-to-ecr
     steps:
+      - name: Test image tag and repository
+        id: test_image_tag_and_repository
+        run: |
+          if $[[ "${{ needs.build-push-image-to-ecr.outputs.tag }}" =~ ${{ env.VERSION_EXPRESSION }} ]]; then
+            echo "Invalid image tag '${{ needs.build-push-image-to-ecr.outputs.tag }}'"
+            echo "::set-output name=run_jobs::false"
+            exit 1
+          elif contains(${{ needs.build-push-image-to-ecr.outputs.registry }}, '.dkr.ecr.'); then
+            echo "Invalid image tag '${{ needs.build-push-image-to-ecr.outputs.tag }}'"
+            echo "::set-output name=run_jobs::false"
+            exit 1
+          elif contains(${{ needs.build-push-image-to-ecr.outputs.registry }}, '.amazonaws.com'); then
+            echo "Invalid image tag '${{ needs.build-push-image-to-ecr.outputs.tag }}'"
+            echo "::set-output name=run_jobs::false"
+            exit 1
+          else
+            echo "::set-output name=run_jobs::true"
+          fi
+
+      - name: Early exit
+        if: steps.test_image_tag_and_repository.outputs.run_jobs == false
+        run: |
+          gh run cancel
+
       - name: Checkout repository
         uses: actions/checkout@v4
 
